package com.example.hassannaqvi.dr_registration.utils;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.Multimap;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * Created by SAJID LATIF on 07-Dec-18.
 */
public class HFs {

    private static Multimap<String, String> data = HashMultimap.create();

    public static List<String> get(String tehsil) {

        data.put("10-A 102", "Bhu 1 A Doshakha");
        data.put("10-A 102", "Falahi Markiz Jindu Peer Kamal");
        data.put("10-A 102", "Rehmeen ClinicandZachaBachaCenter");
        data.put("10-A 102", "Shehzadi clinic private gulshan haider");
        data.put("160P S-11", "Basic Health Unit Chak 158 P");
        data.put("160P S-11", "Basic Health Unit chak 255");
        data.put("160P S-11", "Basic Health Unit Chak No.186/p");
        data.put("178-7R 122", "Bhu 225 A");
        data.put("178-7R 122", "BUU Chak No 147A");
        data.put("178-7R 122", "BHU Chak No 186 7R");
        data.put("228-P", "meternity Home nayazi coloni street no 5");
        data.put("228-P", "Al Fasial clinic");
        data.put("228-P", "Mujeeb wellfare hospital");
        data.put("228-P", "Yunani Dispensari Aziz abad");
        data.put("228-P", "BHU Chack 92-P");
        data.put("228-P", "Ahmad surgical");
        data.put("42-A 103-L", "BHU Chak No 87A");
        data.put("42-A 103-L", "BHU Chak No 150A");
        data.put("42-A 103-L", "BHU 42 A Chak 42A");
        data.put("46-A 101", "BHU chak no 45A");
        data.put("46-A 101", "BHU Chak No 25A");
        data.put("565TDA", "BHU 576 TDA");
        data.put("632TDA", "BHU 531TDA");
        data.put("632TDA", "GRD 535TDA");
        data.put("632TDA", "BHU 632TDA");
        data.put("71-B", "janh town mostafa clenic	");
        data.put("71-B", "Al noor Hospital	");
        data.put("71-B", "THQ	");
        data.put("71-B", "Ferdos clinic and maternity home	");
        data.put("71-B", "Awami Hospitel  and Maternity Home	");
        data.put("71-B", "MCWAK MCH Center	");
        data.put("71-B", "Mother and Child Health Center	");
        data.put("71-B", "Gafoor Clinic house no 8 street no 2 nawan kot road	");
        data.put("71-B", "Alharam clinic	");
        data.put("71-B", "Temoor clinic and Maternity Home	");
        data.put("71-B", "Fasiel Hospital	");
        data.put("71-B Ward No.7", "syed Hoapital zahir peer road adda zahir peer khan pur	");
        data.put("73-B", "Al kosar maternity home new galla mandi	");
        data.put("84-P", "Family Hospital	");
        data.put("84-P", "BHU Chak No 100/p	");
        data.put("84-P", "alkhaar clinic colony no 2 near gov girls school	");
        data.put("84-P", "abu zahabi colony Dispensari	");
        data.put("84-P", "lateef maternity home	");
        data.put("Abad", "GD kando	");
        data.put("Abad", "GD mir muhammad kulhoro	");
        data.put("Abadpur	", "BHU Abad Pur	");
        data.put("Abadpur	", "Ayesha maternity home	");
        data.put("Abadpur	", "Rural Dispensary Dolat Pur	");
        data.put("Abdul Bari", "BHU muhammad sadiq umrani	");
        data.put("Abrahim Wali", "BHU MOCHI wala");
        data.put("Adam Sahaba S-12", "Basic Health Unit Chak 148 P	");
        data.put("Ahmad Ali Lar L-121", "Basic Health Unit Zamin Shah	");
        data.put("Ahmad pur Lamma", "Rural Health Center Ahmad Pur lama	");
        data.put("Ahmad pur Lamma", "Sumaira Maternity Home Ahmad Pur Lama Road Near Dar ur Shifa Trust Maternity Home");
        data.put("Ahmad pur Lamma", "Maternity home Mahla popaliya	");
        data.put("Ahmedabad", "BHU Village Ahmedabad");
        data.put("Aitbar Khan Chandio", "balkeesq maternity home");
        data.put("Aitbar Khan Chandio", "GD Dhing");
        data.put("Aitbar Khan Chandio", "aamina clinic");
        data.put("Aitbar Khan Chandio", "alyas maternity home");
        data.put("Akram Abad 43", "Rural Dispensari Basti Nory Wali");
        data.put("Akram Abad 43", "RD Bahudi Pur Machian");
        data.put("Akram Abad 43", "Iqbal memorial Hospital Ayshia clinic");
        data.put("Akram Abad 43", "BHU Adam wali	");
        data.put("Ali Abad", "CD Qadir Abad");
        data.put("Ali Abad", "BHU Behram Khan Buledi");
        data.put("Ali Abad Jamali", "CD Haji Shabir Umrani");
        data.put("Ali Abad Jamali", "BHU Noor Muhammad Khan Jamali");
        data.put("Ali Abad Jamali", "DrZahid Hussain Clinic");
        data.put("Ali Abad Jamali", "50 Beded Labour Hospital");
        data.put("Ali Abad Jamali", "BHU Ali Abad Jamali");
        data.put("Ali Abad Jamali", "c d sardar rustam khan jamali");
        data.put("Ali Pur", "Tahir clinic");
        data.put("Ali Pur", "Al Fatima Hospital");
        data.put("Ali Pur", "Indus hospital");
        data.put("Ali Pur", "Al Rehman hospital");
        data.put("Ali Pur", "Al Shawar Memorial hospital");
        data.put("Ali Pur", "BHU");
        data.put("Ali Pur", "Sultan surgycal hospital");
        data.put("Ali Pur", "New Malik Surgical Hospital");
        data.put("Ali Pur", "Al Hussian Medicare");
        data.put("Ali Pur", "BHU faqeer Shah");
        data.put("Ali Pur", "BHU ali wali");
        data.put("Ali Pur", "Khan Clinic");
        data.put("Alipur Urban", "THQ Ali Pur");
        data.put("Alipur Urban", "Amina Riyasat clinic");
        data.put("Alipur Urban", "MCH Center");
        data.put("Alipur Urban", "Abbas clinic and meternity home");
        data.put("Alipur Urban", "Rahnuma family Health Clinic");
        data.put("Alipur Urban", "Al majeed memorial meternity home and zacha bacha center");
        data.put("Alipur Urban", "Al Ahd complex");
        data.put("Alipur Urban", "Yasir Altaf Hospital");
        data.put("Alipur Urban", "Manzoor mariyam children and gaeny clinic");
        data.put("Alipur Urban", "Fatima Zahra Hospital");
        data.put("Alipur Urban", "Al Noor Clinic");
        data.put("Allah Abad", "bismillaha");
        data.put("Allah Abad", "BHU tamboo");
        data.put("Allah Abad 113", "RHC ALLAHABAD");
        data.put("Allah Abad 113", "BHU ghoth mahe");
        data.put("Alurid", "BHU");
        data.put("Alurid", "Lasoori");
        data.put("Ameen Garh", "BHU khar pur khadli");
        data.put("Ameen Garh", "Najma maternity home");
        data.put("Ameen Garh", "Ayesha maternity home");
        data.put("Amin Abad L-109", "Bhu amena bad");
        data.put("Amin Abad L-121", "Ameena MaternityHome");
        data.put("Amin Abad L-121", "Rural Dispensory MoriKhichi");
        data.put("Amman Garh R-65", "BHU Basti Kacha");
        data.put("Amman Garh R-65", "BHU BASTI RAEES GHULAM RASOOL");
        data.put("Amman Garh R-65", "Alrahab Hospital");
        data.put("Azeem Shah", "RD Basti Azeem Sha");
        data.put("Azeem Shah", "BHU Chak no 112 NP");
        data.put("Baaz Wala", "BHU Belay wala");
        data.put("Badin-I", "Aqsa hospital");
        data.put("Badin-I", "SHEHBAZ CHILD CARE HOSPITAL");
        data.put("Badin-I", "BHITTAI CLINIC");
        data.put("Badin-I", "DR MOULA BUX JAFFERY MEMORIAL HOSPITAL");
        data.put("Badin-I", "HASSAN MEDICARE");
        data.put("Badin-I", "ZULIFQAR CLINIC");
        data.put("Badin-I", "SHABEER HOSPITAL AND MAYERNITY HOME");
        data.put("Badin-I", "MASOOMAIN CLINIC");
        data.put("Badin-III", "MALEER CLINIC");
        data.put("Badin-III", "khalil clanic");
        data.put("Badin-III", "ANUM MAYERNITY HOME");
        data.put("Badin-III", "Perhiar clinic");
        data.put("Badin-III", "FARHAAD CLINIC");
        data.put("Badin-III", "FAWAD CLINIC");
        data.put("Badin-III", "HASSAN HOSPITAL");
        data.put("Badin-III", "zenaib maternity home");
        data.put("Badin-III", "Sindh clinic");
        data.put("Badin-III", "Mehreen Hospital");
        data.put("Badin-III", "ABDUL RAZAQUE CLINIC");
        data.put("Badin-III", "JEELANI MEDICAL CLINIC");
        data.put("Badli Sharif R-45", "BHU Badli sharif");
        data.put("Bagh Head", "MCH CENTRE KANDRI");
        data.put("Bagh Head", "CD Kandri");
        data.put("Bagh Head", "BHU Bagh Head");
        data.put("Bagho Bahar", "RHC Bagho Bahar");
        data.put("Bago Daro", "BHU Mirpur");
        data.put("Bahishti 62", "RD shah Garh");
        data.put("Bahishti 62", "BHU Bismillah pur");
        data.put("Bahishti 62", "BHU  Bahishti");
        data.put("Bahoudi Pur Qurashian 50", "BHU kot huq Nawaz");
        data.put("Bahram Hethiyon", "benazir clinic");
        data.put("Bahram Hethiyon", "marjan maternity home");
        data.put("Bahram Hethiyon", "abid clanic");
        data.put("Bahram Hethiyon", "raja clanic");
        data.put("Bahram Hethiyon", "sadam clinic	");
        data.put("Bahram Hethiyon", "muzmil clinic	");
        data.put("Bahram Hethiyon", "Salman clinic	");
        data.put("Bahram Hethiyon", "ahsan maternity home	");
        data.put("Bahram Hethiyon", "bismillah clinic	");
        data.put("Bahram Hethiyon", "kousar clanic	");
        data.put("Bahram Hethiyon", "zahoor clanic	");
        data.put("Bahram Hethiyon", "farhan clinic	");
        data.put("Bahram Hethiyon", "karachi clinic	");
        data.put("Bahram Hethiyon", "GD neo tharo	");
        data.put("Bahram Hethiyon", "hakeem maternity home	");
        data.put("Bahram Hethiyon", "prince sarmad	");
        data.put("Bahram Hethiyon", "samad meternity home bahram	");
        data.put("Bahram Hethiyon", "Dua clinic");
        data.put("Bair Band", "BHU kotla laal shah");
        data.put("Bait Mulan Wali", "GRD");
        data.put("Bait Qaim wala", "BHU tounsa birj colony	");
        data.put("Bait Qaim wala", "GRD chakar dari	");
        data.put("Bait Ram Pur", "Usman Haider Maternity home	");
        data.put("Bait Ram Pur", "BHU abrar londi patafi	");
        data.put("Bait Ram Pur", "BHU Bait rampur	");
        data.put("Bakkani", "BHU Bait Drai");
        data.put("Band Manik", "CD Javid Ahmed Khosa	");
        data.put("Basira", "Hasnat medical centre	");
        data.put("Basira", "Ali Surgical Center	");
        data.put("Basti Kharak", "BHU Makwal	");
        data.put("Basti Kharak", "BHU dewala	");
        data.put("Baz Wala	", "	Rahnuma family health clinic	");
        data.put("Baz Wala	", "	BHU Marian	");
        data.put("Bedar	", "	babal khan clinic	");
        data.put("Bedar	", "	al shafa clinic	");
        data.put("Beer Sharif	", "	Beer sharif	");
        data.put("Beer Sharif	", "	malook maternity home	");
        data.put("Beet Mir Hazar Khan	", "	Bait Mir Hazar khan	");
        data.put("Bela	", "	lassi clinic	");
        data.put("Bela	", "	al raheem medicl	");
        data.put("Bela	", "	khadm hussain medical centre	");
        data.put("Bela	", "	al abid clinic	");
        data.put("Bela	", "	BHU balochi goth	");
        data.put("Bela	", "	ghousia medical center	");
        data.put("Bela	", "	Civil hospital bela	");
        data.put("Bela	", "	new bolan medical centre	");
        data.put("Belay Wala	", "	BHU Damar wala shumali	");
        data.put("Ber	", "	basit clanic	");
        data.put("Ber	", "	kamtan clanic	");
        data.put("Bhong 21	", "	Basic health unit	");
        data.put("Bhong 21	", "	Basic Health Unit Garhi Khair Muhammad Jhak	");
        data.put("Bhutawahan 28	", "	Basic Health Unit Muhammad Nawaz Wasa	");
        data.put("Bhutta Pur	", "	BHU Bhutta Pur	");
        data.put("Binda Ishaq	", "	RD binda ishaq	");
        data.put("Binda Ishaq	", "	GRD Basti Allah bux	");
        data.put("Boohar	", "	GD noor muhammad shaikh	");
        data.put("Boohar	", "	erum clinic	");
        data.put("Bulaqi Wali 53	", "	BHU chack abbas	");
        data.put("Cattle Farm	", "	BHU Cattle Farm	");
        data.put("Cattle Farm	", "	bhu dr aziz ullah satakazi	");
        data.put("Cattle Farm	", "	noor medical clinic	");
        data.put("Cattle Farm	", "	cd sikandar jamali	");
        data.put("Cattle Farm	", "	al hussani clinic	");
        data.put("Cattle Farm	", "	CD zulfiqar abad	");
        data.put("Chachran Sharif 85	", "	BHU Mohalla Ghorri Chachran Sharif 85	");
        data.put("Chachran Sharif 85	", "	RD Ahmed Kuden	");
        data.put("Chack Frazi	", "	BHU chak farazi	");
        data.put("Chak No. 105-P	", "	BHU chack No. 107 P	");
        data.put("Chak No. 105-P	", "	Dispensary 106-P	");
        data.put("Chak No. 105-P	", "	MCH	");
        data.put("Chak No. 105-P	", "	RD 91 p	");
        data.put("CHAK No. 139-P	", "	RHC Manthar	");
        data.put("CHAK No. 139-P	", "	RD chak no 126p	");
        data.put("Chak No. 173-P	", "	Rural Health Centr chak no 173 p	");
        data.put("Chak No. 264-P	", "	Basic Health Unit 264 P	");
        data.put("Chak No. 264-P S-24	", "	Rural Unani Dispensary	");
        data.put("Chak No. 264-P S-24	", "	basic health unit chak no 206 p	");
        data.put("Chak No. 45-P	", "	BHU chak no 45 p	");
        data.put("Chak No. 51-P	", "	RD Abu zabi colony no 1	");
        data.put("Chak No. 51-P	", "	Sana Medi care	");
        data.put("Chak No. 51-P	", "	bhu chack no 52p gulmarg	");
        data.put("Chak No. 51-P	", "	Aiman Hospital	");
        data.put("Chak No. 68-A	", "	BHU Chak No 79	");
        data.put("Chak No. 68-A	", "	Bushra Maternity Home Chak No69A	");
        data.put("Chak No. 68-A	", "	RHC FEROZA	");
        data.put("Chak No. 68-A	", "	Rural Dispensory	");
        data.put("Chalgri	", "	bhu ismail chalgri	");
        data.put("Chalgri	", "	CD Bachal Brohi	");
        data.put("Chandia K-85	", "	BHU Ghous por	");
        data.put("Chandia K-85	", "	BHU Moza Khotli Morad Head Langi War	");
        data.put("Chandia K-85	", "	Rular dispensery soomaka	");
        data.put("City 02	", "	MCH muzffar garh	");
        data.put("City 02	", "	Alhameed medical services	");
        data.put("City 02	", "	Minhaj Clinic	");
        data.put("City 02	", "	Alshifa Gyni cear center	");
        data.put("City 02	", "	Abdullah clinic	");
        data.put("City 02	", "	sajda clinic	");
        data.put("City 02	", "	DHQ	");
        data.put("City 03	", "	Abdullah clinic	");
        data.put("City 31-B	", "	MCH center noore wali	");
        data.put("City 31-B	", "	Hania surgical	");
        data.put("City 31-B	", "	Al shifa House	");
        data.put("City 31-B	", "	Al Qadir madi care	");
        data.put("City 31-B	", "	Lala compalex	");
        data.put("City 31-B	", "	MCH	");
        data.put("City 31-B	", "	Zanaib hospital	");
        data.put("City 31-B	", "	naz clinic	");
        data.put("City 31-B	", "	shaikh zaid hospital	");
        data.put("City 31-B	", "	National clinic	");
        data.put("City 31-B	", "	Azam hospital	");
        data.put("City 31-B	", "	Ayesha Saddiqa maternity home	");
        data.put("City 31-B	", "	Humera maternity home	");
        data.put("City A	", "	Mother and Child Health Center Basti Mian Sahib	");
        data.put("City A	", "	ali clinic ilyass colony	");
        data.put("City A	", "	Al Ahmad Hospital	");
        data.put("City A	", "	Kanwal Clinic Street No 1 Mujahid Colony Katcha Sahi Road  Sadiq Abad	");
        data.put("City A	", "	private clinic	");
        data.put("City A	", "	Fareeha maternity home community mid wife	");
        data.put("City A	", "	Saqlain Hospital	");
        data.put("City A	", "	family health centr	");
        data.put("City A	", "	Tehsil Head Quarter Hospital Sadiq Abad Hospital R	");
        data.put("City F	", "	Zulafqar Clinic And Maternity Home Haq Town Sadiq Abad	");
        data.put("CITY LQP	", "	Tehsil Head Quarter Liaquatpur	");
        data.put("CITY LQP	", "	Baby Care Clinic 87 BANK liaquatpur	");
        data.put("CITY LQP	", "	Raffia begam Hospital	");
        data.put("CITY LQP	", "	Asfia Hospital	");
        data.put("CITY LQP	", "	city hospital liaquatpur	");
        data.put("CITY LQP	", "	Zubaida Memorial Hospital	");
        data.put("CITY LQP	", "	Saad Abdullah Surgical Hospital 87 Bank Road Liaquatpur	");
        data.put("CITY LQP	", "	shahida surgical and maternity home	");
        data.put("CITY LQP	", "	Maan MaternityHome87A Bank road liaquatpur	");
        data.put("CITY LQP	", "	akbar medical center	");
        data.put("CSS	", "	rehmat rehman	");
        data.put("CSS	", "	abida nasreen clinic	");
        data.put("CSS	", "	fatima miternity home	");
        data.put("CSS	", "	al rabia trust clinic	");
        data.put("CSS	", "	BHU 133ML	");
        data.put("CSS	", "	THQ css	");
        data.put("Damar Wala	", "	BHU Qader pur	");
        data.put("Dari Azeem Khan	", "	BHU Dari Azeem Khan	");
        data.put("Darin	", "	BHU Daani	");
        data.put("Dashti L-108	", "	BHU Dashti Moza Dashti	");
        data.put("DDPannah	", "	HRC DDP	");
        data.put("DDPannah	", "	urooj fatima clinic	");
        data.put("DDPannah	", "	hashmi clinic	");
        data.put("DDPannah	", "	Alhuda khitmat clinic	");
        data.put("DDPannah	", "	Alshifa maternity home	");
        data.put("DDPannah	", "	suleman surgecal hospital	");
        data.put("DDPannah	", "	alshifa clinic	");
        data.put("Deera	", "	saqib clinic	");
        data.put("Deera	", "	BHU maroon dera	");
        data.put("Deera	", "	habib maternity home	");
        data.put("Dei Jarkas	", "	DEWAAN CLINIC	");
        data.put("Dhandi-23	", "	Basic Health Unit Bindoor Abasian	");
        data.put("Dhigano Khan	", "	GD kot lalbux maheser	");
        data.put("Dinpur Sharif	", "	BHU Dinpor Sharif chak 99	");
        data.put("Dinpur Sharif	", "	Shamshad Matrenity Home	");
        data.put("Dinpur Sharif	", "	RD Dinpur Sharif	");
        data.put("Doger klasra	", "	BHU khar gharbi dogar clasra	");
        data.put("Drigrah	", "	basic  health unit	");
        data.put("Drigrah	", "	Rural Health Dispensary	");
        data.put("Dufli Kabeer Khan 120	", "	Rural Dispensory Dufli Kabeer	");
        data.put("Dufli Kabeer Khan 120	", "	Basic Health Unit Unran	");
        data.put("Duraji	", "	CD Deewana shah	");
        data.put("Duraji	", "	RHC Dureji	");
        data.put("Duraji	", "	CD Hinidan	");
        data.put("Duraji	", "	CD Suthnak	");
        data.put("Duraji	", "	CD Umed abad	");
        data.put("Duraji	", "	CD Sorh	");
        data.put("Ehsan Pur	", "	Bhu ehsan pur	");
        data.put("Ehsan Pur	", "	GRD ehsan pur	");
        data.put("Faizabad Jamali	", "	BHU Allah Dina Rind	");
        data.put("Faizabad Jamali	", "	BHU Muhammad Yakoob Pandrani	");
        data.put("Faizabad Jamali	", "	CD Faizabad	");
        data.put("Fateh Pur Janoobi	", "	BHU	");
        data.put("Gadani	", "	MCH Gadani	");
        data.put("Gadani	", "	BHU Gadani	");
        data.put("Gadani	", "	BHU Pota hoth	");
        data.put("Gadani	", "	RHC Gadani	");
        data.put("Gador	", "	BHU Memmodani village	");
        data.put("Gador	", "	CD Gadoore	");
        data.put("Gador	", "	BHU ismailani village	");
        data.put("Gador	", "	bhu nimani goth	");
        data.put("Gador	", "	BHU mangiya	");
        data.put("Gaji Khuhawar	", "	farhan clinic	");
        data.put("Gaji Khuhawar	", "	lukman clinic	");
        data.put("Gaji Khuhawar	", "	raja waseem clinic	");
        data.put("Gaji Khuhawar	", "	bakhat clinic	");
        data.put("Gaji Khuhawar	", "	liaqat clinic	");
        data.put("Gaji Khuhawar	", "	Nad ali clinic	");
        data.put("Gaji Khuhawar	", "	naeem clinic	");
        data.put("Gaji Khuhawar	", "	hyder clinic	");
        data.put("Gaji Khuhawar	", "	jabir clinic	");
        data.put("Gaji Khuhawar	", "	GD sawi chandio	");
        data.put("Galor Masuu Khan R-55	", "	BHU Adam Arain	");
        data.put("Gandakha	", "	BHU Gandakha	");
        data.put("Gandakha	", "	Irum Clinic	");
        data.put("Gandakha	", "	CD Ghulam Muhammad	");
        data.put("Gandakha	", "	BHU Chowki Jamali	");
        data.put("Gandakha	", "	HAD Dr Taj Muhammad Jamali	");
        data.put("Gandakha	", "	Shuhab Clinic	");
        data.put("Gandakha	", "	Balochistan Clinic	");
        data.put("Ganga	", "	BHU qadir pur saleh	");
        data.put("Garay Wahin	", "	BHU Kamal Pur Patni	");
        data.put("Garay Wahin	", "	BHU giray wahin	");
        data.put("Garhi Ikhtiar Khan	", "	BHU Gerhi Ikhtiar khan	");
        data.put("Gehna Lar	", "	BHU Chak no 94 np Gehna Lar	");
        data.put("Gehna Lar	", "	BHU Gehna Lar	");
        data.put("Ghaibi Dero	", "	BHU gaibi dero	");
        data.put("Ghalwan", "Ali Surgical Hospital	");
        data.put("Ghalwan", "Jinnah Hospital	");
        data.put("Ghalwan", "Life care health center	");
        data.put("Ghalwan", "Hassan Clinic	");
        data.put("Ghalwan", "Al Safa Surgical Hospital	");
        data.put("Ghalwan", "Medi clinic	");
        data.put("Gharbi", "MCH Center Dera Murad Jamali	");
        data.put("Gharbi", "al shafa medical centre	");
        data.put("Gharbi", "larkana clinic	");
        data.put("Gharbi", "haq baho clinic	");
        data.put("Gharbi", "new baby careclinic	");
        data.put("Gharbi", "al saeed clinic	");
        data.put("Gharbi", "shah zaib clinic	");
        data.put("Gharbi", "bismillaha clinic	");
        data.put("Gharbi", "al naseeb clinic	");
        data.put("Gharbi", "al maqbool clinic	");
        data.put("Gharbi", "Al Sattar Clinic	");
        data.put("Gharbi", "Bukhari Clinic	");
        data.put("Gharbi", "al qadir clinic	");
        data.put("Gharbi", "al Rahman clinic	");
        data.put("Gharbi", "ayan medical clinic	");
        data.put("Gharbi", "Sundrani Clinic	");
        data.put("Gharbi", "new national clinic	");
        data.put("Gharbi", "bismillah alqadir clinic	");
        data.put("Gharbi", "baloch clinic	");
        data.put("Gharbi", "abdullah clinic	");
        data.put("Gharbi", "al noor clinic	");
        data.put("Gharbi", "awami clinic	");
        data.put("Gharbi", "Magsi Clinic	");
        data.put("Gharbi", "fazal maternity clinic	");
        data.put("Gharbi", "bahrani clinic	");
        data.put("Gharbi", "pir suhri clinic	");
        data.put("Gharbi", "al shafa clinic	");
        data.put("Gharbi", "balochistan medical facility	");
        data.put("Gharbi", "al rehman medical clinic	");
        data.put("Gharbi", "alshafa clinic	");
        data.put("Gharbi", "al rahman clinic	");
        data.put("Gharbi", "DHQ Hospital Dera Murad Jamali	");
        data.put("Gharbi", "faiz clinic	");
        data.put("Gharbi", "fatma maternity clinic	");
        data.put("Gharbi", "gul madi care clinic	");
        data.put("Gharbi", "hasnain medical center	");
        data.put("Gharbi", "baloch clinic	");
        data.put("Ghazanfar Garh	", "	GRD	");
        data.put("Ghazanfar Garh	", "	GRD Dair wadoo	");
        data.put("Ghazipur	", "	BHU Ghazi pur	");
        data.put("Ghooka L-111	", "	BHU moza hrrona bad bsti kotla wlehan	");
        data.put("Ghooka L-111	", "	Sonia Bakht Clinic Maternity Home	");
        data.put("Ghooka L-111	", "	Rural Dispensory Metla	");
        data.put("Golarchi	", "	THQ GHOLARCHI	");
        data.put("Golarchi	", "	LARAIB CLINIC	");
        data.put("Golarchi	", "	Hoo Allshaffi	");
        data.put("Golarchi	", "	MEHRAN CLINIC	");
        data.put("Golarchi	", "	Rameez Clanic	");
        data.put("Golarchi	", "	AL HAMZA CLINIC	");
        data.put("Golarchi	", "	MEHRAN CLINIC	");
        data.put("Golarchi	", "	Alfareed Clanic	");
        data.put("Golarchi	", "	ABBASSI CLINIC	");
        data.put("Golarchi	", "	alshafa	");
        data.put("Golarchi	", "	LATIF CLINIC	");
        data.put("Goth Jangoo 9	", "	basic health unit basti sabzal khan	");
        data.put("Goth Jangoo 9	", "	Basic Health Unit Begar Garhi	");
        data.put("Gujraat	", "	alsaif gayni hospital	");
        data.put("Gujraat	", "	asma bano clinic	");
        data.put("Gujraat	", "	kneez fatima clinic	");
        data.put("Gujraat	", "	almsoom clinic	");
        data.put("Gujri	", "	Al Shifa Clinic	");
        data.put("Gujri	", "	shafi clinic	");
        data.put("Gul Muhammad Langha L-106	", "	BHU Shehbaz Pur Sharqi	");
        data.put("Gull Walla	", "	BHU	");
        data.put("Gull Walla	", "	RD darbar Muhammad moosa	");
        data.put("Hadeero	", "	BHU Ali Hassan Jamali	");
        data.put("Hadeero	", "	Abdul Khaliq Jamali	");
        data.put("Hafeezabad	", "	c d hafiz abad	");
        data.put("Haji Pur	", "	BHU Haji Pur	");
        data.put("Haji Pur	", "	RD missan Abad	");
        data.put("Haji Pur	", "	Syed Clinic and Maternity Home	");
        data.put("HANJRAI	", "	GRD bahar wli	");
        data.put("HANJRAI	", "	BHU kanjo wala	");
        data.put("HANJRAI	", "	RD hinjri	");
        data.put("Hara sithar	", "	CD Hara sethar	");
        data.put("Hara sithar	", "	BHU bambor	");
        data.put("Hassan pir	", "	Imran clinic	");
        data.put("Hassan pir	", "	BHU Lang Lohar	");
        data.put("Hassan pir	", "	BHI Hassan abad	");
        data.put("Hayat Lar 112	", "	BHU Arif Baloch	");
        data.put("Hayat Lar 112	", "	RD Hayat Lar 112	");
        data.put("Hayat Lar 112	", "	Akasha Maternity Home Near by pas road Feroza	");
        data.put("Hayat Lar 112	", "	Tahir General Hospital near RHCF EROZA	");
        data.put("Hayat Lar 112	", "	BHU Haveli Ghareeb Shah	");
        data.put("Hub	", "	abdul ghani memorial clinic	");
        data.put("Hub	", "	National medical center	");
        data.put("Hub	", "	hamal clinic	");
        data.put("Hub	", "	Jam Ghulam Qadir Govt hospital Hub	");
        data.put("Hub	", "	MCH centre Hub	");
        data.put("Hub	", "	Qazi medical center	");
        data.put("Hub	", "	bolan clinic	");
        data.put("Hub	", "	Asif clinic	");
        data.put("Hub	", "	alkhaliq clinic	");
        data.put("Hub	", "	Arsalan Clinic	");
        data.put("Hub	", "	Urooj medical center	");
        data.put("Hub	", "	fatima charity clinic	");
        data.put("Hub	", "	shah clinic	");
        data.put("Hub	", "	alshifa clinic	");
        data.put("Hub	", "	sapna medical center	");
        data.put("Hub	", "	Baloch clinic	");
        data.put("Hub	", "	sehrish clinic	");
        data.put("Hub	", "	marvi maternity clinic	");
        data.put("Hub Co	", "	BHU Goth Allana Gador	");
        data.put("J.K Laghari	", "	RHC jafer khan laghari	");
        data.put("Jaggat Pur	", "	bhu jaggatpur	");
        data.put("Jaggat Pur	", "	Eman clinic	");
        data.put("Jajjah Abbasian	", "	RD Jajjah Abbasian	");
        data.put("Jajjah Abbasian	", "	BHU malik pur	");
        data.put("Jajjah Abbasian	", "	Mehwish Maternity Home	");
        data.put("Jajjah Abbasian	", "	Ali Maternity Home	");
        data.put("Jamal Din Wali	", "	Rural Health Centre Jmal Deen Wali	");
        data.put("Jamal Din Wali	", "	Nazeer Surgical Centre and Maternity Home	");
        data.put("Jamali	", "	RHC umed ali junejo	");
        data.put("Jamali	", "	GD muhammad khan bhutto	");
        data.put("Janpur 110	", "	Rural Dispensory	");
        data.put("Janpur 110	", "	BHU Janpur	");
        data.put("Jatoi	", "	Shahida Safdar surgical hospital	");
        data.put("Jatoi	", "	Al quresh surgical hospital jatoi	");
        data.put("Jatoi	", "	THQ jatoi	");
        data.put("Jatoi Shumali	", "	meerab clinic and maternity home	");
        data.put("Jean Abro	", "	sikander clinic	");
        data.put("Jean Abro	", "	liaquat clinic	");
        data.put("Jean Abro	", "	Alhuram shafa khana	");
        data.put("Jean Abro	", "	G.D Baig Mohammad Sangah	");
        data.put("Jean Abro	", "	zameera maternity home	");
        data.put("Jean Abro	", "	Ali maternity home	");
        data.put("Jean Abro	", "	G.D Naurang Sharif	");
        data.put("Jean Abro	", "	G.D Jean Abro	");
        data.put("Jetha Bhutta	", "	RD Jetha Bhutta	");
        data.put("Jetha Bhutta	", "	Atar Medicose	");
        data.put("Jetha Bhutta	", "	BHU Chak NO.1/P Jetha Bhutta	");
        data.put("Jetha Bhutta	", "	Kareem Bux Hospital	");
        data.put("Jhalareen	", "	BHU Hamzay wali	");
        data.put("Jhoke Ghulab Shah 105	", "	Bhu jhok gulb shah	");
        data.put("Jhoke Ghulab Shah 105	", "	BHU Jhok Gulab shah	");
        data.put("Jhol	", "	al shafa clinic	");
        data.put("Jhol	", "	RHC jhole	");
        data.put("Jhol	", "	mughal clinic and maternity home	");
        data.put("Jhoran	", "	BHU Thakal Arain	");
        data.put("Jhudair II	", "	alshafa clinic	");
        data.put("Jhudair II	", "	BHU sabz ali umrani	");
        data.put("Jhudair II	", "	BHU dildar khan umrani	");
        data.put("Jhudair N	", "	BHU Kot Mengal	");
        data.put("Jhuggi Wala	", "	Arbi zacha bacha center	");
        data.put("Jhuggi Wala	", "	BHU Jhuggi wala	");
        data.put("Jhuggi Wala	", "	Dhanak Health care	");
        data.put("Kadhan	", "	RHC KHADHAN	");
        data.put("Kadi Qazia	", "	Ali Clanic	");
        data.put("Kadi Qazia	", "	AL SHIFFA CLINIC MORJHAR	");
        data.put("Kandiari	", "	awami clinic	");
        data.put("Kandiari	", "	Sharda Clinic	");
        data.put("Kandiari	", "	Magsi Clinic	");
        data.put("Kandiari	", "	Aftab Clinic	");
        data.put("Kandiari	", "	karachi clinic	");
        data.put("Kandiari	", "	kirshna clinic	");
        data.put("Kandiari	", "	RHC kandiyari	");
        data.put("Kanhar	", "	medical dispensary	");
        data.put("Kanraj	", "	BHU Goth Haji Leema	");
        data.put("Kanraj	", "	BHU Sahib khan	");
        data.put("Kanraj	", "	BHU Umar goth	");
        data.put("Kanraj	", "	BHU Roch kund	");
        data.put("Kanraj	", "	CD Kanraj	");
        data.put("Karam Dad Qureshi	", "	Umar medical centre	");
        data.put("Karam Dad Qureshi	", "	BHU KD Qureshi	");
        data.put("Karam Dad Qureshi	", "	BHU shareef chagra	");
        data.put("Karam Dad Qureshi	", "	Qurat ul ain clinic	");
        data.put("Karam Dad Qureshi	", "	Ittifaq Surgical Hospital	");
        data.put("Karam Dad Qureshi	", "	Zuhra clinic	");
        data.put("Karia Pheri	", "	BHU Baghtail	");
        data.put("Kario Ghahwer	", "	sindhu	");
        data.put("Kario Ghahwer	", "	kewal clinic	");
        data.put("Kario Ghahwer	", "	AWAAMI CLINIC	");
        data.put("Kario Ghahwer	", "	AL SHAFFIQUE CLINIC	");
        data.put("Kario Ghahwer	", "	rawal clanic	");
        data.put("Kario Ghahwer	", "	mehran clanic	");
        data.put("Kario Ghahwer	", "	ALI CLINIC	");
        data.put("Kario Ghahwer	", "	IRFAN HEALTH CARE CLINIC	");
        data.put("Kario Ghahwer	", "	RHC KARIO GHAWER	");
        data.put("Kario Ghahwer	", "	Majid Clanic	");
        data.put("Kario Ghahwer	", "	AL HAFIZ CLINIC	");
        data.put("Kario Ghahwer	", "	DANISH CLINIC	");
        data.put("Kario Ghahwer	", "	manzoor clanic	");
        data.put("Kario Ghahwer	", "	KIRSHNA MATERNITY HOME	");
        data.put("Kario Ghahwer	", "	aijazhospital and matarnity home	");
        data.put("Kario Ghahwer	", "	dua metarnity home	");
        data.put("Kario Ghahwer	", "	naresh	");
        data.put("Kathor	", "	CD kud	");
        data.put("Kathor	", "	CD kathorh village	");
        data.put("Kathor	", "	BHU kud karkhi	");
        data.put("Kathor	", "	BHU dan kathorh village	");
        data.put("Kathor	", "	CD arif wala	");
        data.put("Kathor	", "	BHU Kanar	");
        data.put("Kathor	", "	BHU tharara	");
        data.put("Kathor	", "	BHU gundacha	");
        data.put("Kehnwari	", "	CD Wasra Landhi	");
        data.put("Kehnwari	", "	CD Bohar	");
        data.put("Kehnwari	", "	BHU Deerja	");
        data.put("Kehnwari	", "	BHU Sand	");
        data.put("Khabar	", "	Gd dalil buriro	");
        data.put("Khadhero	", "	MEHRAN CLININ	");
        data.put("Khadhero	", "	MARVI MEDICARE  HOSPITAL	");
        data.put("Khadhero	", "	HOMEO CLINIC	");
        data.put("Khadhero	", "	RHC DEHEE	");
        data.put("Khadro	", "	Hameer faqeer clinic	");
        data.put("Khadro	", "	Ayaz clinic	");
        data.put("Khadro	", "	District Council dispensary	");
        data.put("Khadro	", "	Bukhari clinic	");
        data.put("Khadro	", "	Kartar clinic	");
        data.put("Khadro	", "	Bhittai clinic	");
        data.put("Khadro	", "	New hameer faqeer clinic	");
        data.put("Khadro	", "	Syed clinic	");
        data.put("Khadwari	", "	Al Muzamil clinic	");
        data.put("Khadwari	", "	Umar clinic	");
        data.put("Khair pur joso	", "	GD dedar	");
        data.put("Khairpur Sadat	", "	Nighat batool memorial hospital	");
        data.put("Khairpur Sadat	", "	RHC khair pur Sadat	");
        data.put("Khairpur Sadat	", "	Hamza Meternity Home	");
        data.put("Khalifo Qasim	", "	azadar clanic	");
        data.put("Khalifo Qasim	", "	AL SHIFFA CLINIC	");
        data.put("Khalifo Qasim	", "	Sindh sukaj calanic	");
        data.put("Khalifo Qasim	", "	AKBAR CLINIC	");
        data.put("Khan Bela	", "	Hamza clinic Rural Health Center Khanbela	");
        data.put("Khan Bela	", "	Mumtaz Maternity Home	");
        data.put("Khan Bela	", "	zain clinic	");
        data.put("Khan Bela	", "	Rural Dispensory	");
        data.put("Khan Bela L-114	", "	Rural Health Center Khanbela	");
        data.put("Khan Pur Jamali	", "	BHU Ghareebabad	");
        data.put("Khan Pur Jamali	", "	haq bahoo clinic	");
        data.put("Khan Pur Jamali	", "	CD khan pur jamali	");
        data.put("Khangarh	", "	RHC khan garh	");
        data.put("Khangarh Doma	", "	BHU	");
        data.put("Khangarh Doma	", "	BHU Ghagri	");
        data.put("Khangarh Doma	", "	BHU Khan pur Nurka	");
        data.put("Khanpur North	", "	bhu khan pur baga sheer	");
        data.put("Khanpur North	", "	BHU khanpur baga sher	");
        data.put("Kharak UC-35	", "	BHU mondka	");
        data.put("Kharos Wah	", "	Irfan	");
        data.put("Kharos Wah	", "	alfarooq clinic	");
        data.put("Khona Tamboo	", "	cd rd 75 haji rasool bux lehri	");
        data.put("Khona Tamboo	", "	RD 40 magsi shakh	");
        data.put("Khona Tamboo	", "	BHU RD 50	");
        data.put("Khorwah	", "	RHC KHANANI JAT	");
        data.put("Khoski	", "	RHC KHOSKI	");
        data.put("Khrose Wah	", "	BHU Allah Dad Umrani	");
        data.put("Khrose Wah	", "	alwahid clinic	");
        data.put("Khrose Wah	", "	cd kharos wah	");
        data.put("Khurkherra	", "	CD khur khera	");
        data.put("Kot Mehdi Shah	", "	rahmaan clinic fatha pur punjabin	");
        data.put("Kot Mehdi Shah	", "	Al khalid hospital	");
        data.put("Kot Mehdi Shah	", "	Bhu fateh pur punjabian	");
        data.put("Kot Samaba	", "	RHC kot samaba	");
        data.put("Kot Sanjar Khan	", "	Basic Health Unit Kot Sanjar Khan	");
        data.put("Kot Sanjar Khan	", "	Rural Dispensary Basti Nehal Khan	");
        data.put("Kotla Ganmon	", "	BHU kotla gammu	");
        data.put("Kotla Pathan	", "	BHU main road of kotla pathan	");
        data.put("Kurkali	", "	dr kirshan chand	");
        data.put("Kurkali	", "	faqeer Muhmmad	");
        data.put("Kurkali	", "	dr kirshan chand	");
        data.put("Kurkali	", "	dr rajesh clinic	");
        data.put("Lakha	", "	farasat clinic	");
        data.put("Lakha	", "	asim clinic	");
        data.put("Lakha	", "	anwar memorial clinic	");
        data.put("Lakha	", "	alshafa maternity home	");
        data.put("Lakha	", "	GD allah rakhyo jalbami	");
        data.put("Lakhra	", "	RHC Lakhra	");
        data.put("Lakhra	", "	Al shifa clinc Lakhra	");
        data.put("Lakhra	", "	BHU oba	");
        data.put("Lalu raunk	", "	mustafa clinic	");
        data.put("Lalu raunk	", "	mehran clinic	");
        data.put("Lalu raunk	", "	Al syed maternity home	");
        data.put("Lalu raunk	", "	urooj  clinic	");
        data.put("Lalu raunk	", "	Ali clinic	");
        data.put("Lalu raunk	", "	al haeeb clinic	");
        data.put("Lalu raunk	", "	sindhu clinic lalu ranak	");
        data.put("Lalu raunk	", "	Allama taraq clinic	");
        data.put("Langer Wah	", "	RD Urla	");
        data.put("Latki	", "	BHU Latki	");
        data.put("Liaquat Pur-98	", "	Salema  Maternity home liquat pur	");
        data.put("Liari	", "	BHU liyari village	");
        data.put("Liari	", "	BHU Phor 2	");
        data.put("Liari	", "	CD Sorabi	");
        data.put("Liari	", "	BHU duba village	");
        data.put("Liari	", "	BHU Phor 1	");
        data.put("Lohi	", "	BHU Lohi	");
        data.put("Lohi	", "	BHU Lak Rohail	");
        data.put("Lohi	", "	CD Behlor	");
        data.put("Luari Sharif	", "	MUHAMMAD TUFAIL	");
        data.put("Luari Sharif	", "	AL RAUF	");
        data.put("Luari Sharif	", "	NOUMAAN CLINIC	");
        data.put("Lundo	", "	GD Khan Rind	");
        data.put("Lundo	", "	GD Umar chutto	");
        data.put("Lundo	", "	GD manhon jamali	");
        data.put("Lutkeran	", "	MCH	");
        data.put("Lutkeran	", "	RD TMA	");
        data.put("Lutkeran	", "	BHU Dasti wala	");
        data.put("Lutkeran	", "	BHU Dasti wala	");
        data.put("Lutkeran	", "	INDUS HOSPITAL	");
        data.put("Lutkeran	", "	RD sheray wali hatti	");
        data.put("Mahra	", "	BHU marha	");
        data.put("Manik Pur	", "	GRD Manik Pur	");
        data.put("Manjhothi	", "	cd mohammad azeem magsi	");
        data.put("Manjhoti	", "	al altaf clinic	");
        data.put("Manjhoti	", "	BHU ahmed shaeed	");
        data.put("Manjhoti	", "	al noor clinic	");
        data.put("Manjhoti	", "	HAD bashir ahmed manjhoti	");
        data.put("Manjoo Shori	", "	bakhtawar medical centre	");
        data.put("Manjoo Shori	", "	RHC manjho shori	");
        data.put("Manjoo Shori	", "	tariq clinic	");
        data.put("Manjoo Shori	", "	al taj clinic	");
        data.put("Manjoo Shori	", "	al mahmood clinic	");
        data.put("Mao Mubarik	", "	BHU Gulshan e Darra	");
        data.put("Mari Allah Bachaya	", "	Rural Dispensery Mud Ilyas	");
        data.put("Mari Allah Bachaya	", "	BHU Mari Allah Bachaya	");
        data.put("Mastoi	", "	GD ubedullah mastoi	");
        data.put("Mastoi	", "	GD ghulam rasool magsi	");
        data.put("Mastoi	", "	GD luqman siyal	");
        data.put("Matli-I	", "	memon hospital	");
        data.put("Matli-I	", "	EHSAAN ABBASS MATERNITY HOME	");
        data.put("Matli-I	", "	MOHSIN CLINIC	");
        data.put("Matli-I	", "	Hina clanic	");
        data.put("Matli-I	", "	THQ MATLI	");
        data.put("Matli-I	", "	MARVI HOSPITAL	");
        data.put("Matli-I	", "	Sunny clanic	");
        data.put("Matli-I	", "	BHURGRI CHARITABLE HOSPITAL	");
        data.put("Matli-I	", "	MUHAMMADI MATERNITY HOME	");
        data.put("Matli-I	", "	Alshafa clanic	");
        data.put("Meer Hazar	", "	salma maternity home	");
        data.put("Meer Hazar	", "	marya zacha bacha center and children cear hospital	");
        data.put("Meer pur bhagal	", "	GRD 513	");
        data.put("Meer pur bhagal	", "	BHU 518TDA	");
        data.put("Mian	", "	government dispensery	");
        data.put("Mian Wali Qureshian	", "	RHC mian Wali Qureshian	");
        data.put("Mian Wali Sheikhan R-52	", "	BHU mian wali sheikhan	");
        data.put("Miandad Chinjni	", "	BHU mian dad chinjni	");
        data.put("Mir Wah	", "	farhan clinic	");
        data.put("Mir Wah	", "	BHU New Mir Wah	");
        data.put("Mir Wah	", "	RHC mir wah	");
        data.put("Miro Khan	", "	balkees maternity home	");
        data.put("Miro Khan	", "	shoib clinic	");
        data.put("Miro Khan	", "	sehrish clinic	");
        data.put("Miro Khan	", "	Sindhu Maternity Home	");
        data.put("Miro Khan	", "	Bismillah Maternity Home	");
        data.put("Miro Khan	", "	Bismillah maternity home	");
        data.put("Miro Khan	", "	sapna maternity home	");
        data.put("Miro Khan	", "	mean road miro khan	");
        data.put("Miro Khan	", "	muswar clinic	");
        data.put("Miro Khan	", "	dua maternity home miro khan	");
        data.put("Miro Khan	", "	abdullah medical center	");
        data.put("Miro Khan	", "	alshafa clinic	");
        data.put("Miro Khan	", "	GD meena	");
        data.put("Miro Khan	", "	THQ miro khan	");
        data.put("Miro Khan	", "	junaid maternity home	");
        data.put("Miro Khan	", "	Hasnan clinic	");
        data.put("Miro Khan	", "	Child health care clinic	");
        data.put("Miro Khan	", "	Dua clinic	");
        data.put("Mohib Shah	", "	Basic Health Unit Kot Sabzal	");
        data.put("Mohib Shah	", "	Basic Health Unit 39 NP	");
        data.put("Moinabad	", "	BHU Muslam town	");
        data.put("Moinabad	", "	RD Moinabad	");
        data.put("Mud Bhora	", "	BHU Mud Bhora	");
        data.put("Mud Wala	", "	Al saad family clinic	");
        data.put("Mud Wala	", "	Sufyan Clinic	");
        data.put("Mud Wala	", "	RD	");
        data.put("Mud Wala	", "	Ata Muhammad khan free dispensery	");
        data.put("Mud Walla	", "	GRD	");
        data.put("Muhammad Daha	", "	BHU muhammad daha	");
        data.put("Muhammad Khan Bhurghari	", "	AL SHIFFA CLINIC	");
        data.put("Muhammad Khan Bhurghari	", "	RHC FAZAL MUHAMMAD TALPUR	");
        data.put("Muhammad Pur 15	", "	Rural Dispensary Basti Jam Muhammad Nawaz Wasa	");
        data.put("Muhammad Pur 15	", "	Basic Health Unit Chak No 26 N P	");
        data.put("Mullan Walli	", "	BHU Chunjan	");
        data.put("Murad Abad	", "	BHU Langar Saraye	");
        data.put("Murad Abad	", "	Bismillah Clinic	");
        data.put("Murad Abad	", "	Langar saray	");
        data.put("Murad Abad	", "	RHC Muradabad	");
        data.put("Murad Abad	", "	GRD Thatta Sialan	");
        data.put("Muradi	", "	imran clinc	");
        data.put("Muradi	", "	aamir maternity home	");
        data.put("Muradi	", "	suhail clinic	");
        data.put("Muradi	", "	karachi clanic	");
        data.put("Muradi	", "	sonia clinic	");
        data.put("Muradi	", "	syed clinic	");
        data.put("Muradi	", "	child Speachialist clanic	");
        data.put("Muradi	", "	jinnah clanic	");
        data.put("Muradi	", "	ali clinic	");
        data.put("Muradi	", "	al hasnain clinic	");
        data.put("Muradi	", "	jhulay laal	");
        data.put("Muradi	", "	jawad maternity home	");
        data.put("Muradi	", "	GD hatum soho	");
        data.put("Muradpur Janobi	", "	BHU khizra Abad	");
        data.put("Muradpur Janobi	", "	RD Meerani	");
        data.put("Murtazabad 51	", "	RD Anwar abad	");
        data.put("Murtazabad 51	", "	BHU murtazabad	");
        data.put("Murtazabad 51	", "	RD Degi Bangla	");
        data.put("Muzaffargarh City 3	", "	Khan clinic	");
        data.put("Muzaffargarh City Bhutta Pur	", "	BHU	");
        data.put("Nakakharri	", "	CD Naka Kharari	");
        data.put("Nasirabad	", "	isra clinic	");
        data.put("Nasirabad	", "	khushbo maternity home	");
        data.put("Nasirabad	", "	sarang clinic	");
        data.put("Nasirabad	", "	fawad maternity home	");
        data.put("Nasirabad	", "	Dua maternity home	");
        data.put("Nasirabad	", "	Gul clinic	");
        data.put("Nasirabad	", "	Abida maternity home	");
        data.put("Nasirabad	", "	Rhc nasirabad	");
        data.put("Nasirabad	", "	naveed clinic	");
        data.put("Nasirabad	", "	tayba maternity home	");
        data.put("Nasirabad	", "	Husna maternity home	");
        data.put("Nawan Kot	", "	RHC Nawan kot	");
        data.put("Nawan Kot	", "	RD  Doda Lar	");
        data.put("Nawazabad	", "	Rural Health Centre Nawaz Abad	");
        data.put("Neelgarh	", "	BHU Bhatta Sheikhain	");
        data.put("Neelgarh	", "	BHU chak no 7 p	");
        data.put("Neelgarh	", "	BHU Chak no 131  1L	");
        data.put("Neelgarh	", "	Family Health Care Center	");
        data.put("Neelgarh	", "	Latif Clinic chak no 136 1L tiba colony	");
        data.put("Nindo	", "	sindhu	");
        data.put("Nindo	", "	mehran chalid care centere	");
        data.put("Nindo	", "	SAKRIA CLINIC	");
        data.put("Nindo	", "	RHC NINDO	");
        data.put("Nindo	", "	Al Mehdi clanic	");
        data.put("Nindo	", "	zulifqar clanic	");
        data.put("Nohan Wali	", "	lashari clinic	");
        data.put("Nohan Wali	", "	BHU Ali Wala	");
        data.put("Nohan Walla	", "	Rural Dispensary	");
        data.put("Nohan Walla	", "	RD	");
        data.put("North Walpat	", "	CD moryani	");
        data.put("North Walpat	", "	BHU Gajari	");
        data.put("Noshki Jadeed	", "	CD Noshki Jadeed	");
        data.put("Pacca Laran L-117	", "	Rural Dispensory Kotla Doulat	");
        data.put("Pacca Laran L-117	", "	BHU Kandani	");
        data.put("Pacca Laran L-117	", "	RHC Pacca Laran	");
        data.put("Pahar Mari	", "	ABID CLINIC	");
        data.put("Pahar Mari	", "	DUA CLINIC	");
        data.put("Pangrio	", "	BHITTAI CLINIC	");
        data.put("Pangrio	", "	batti clanic	");
        data.put("Pangrio	", "	SAMAN SARKAR  MATERNITY HOME	");
        data.put("Pangrio	", "	KHUWAJA CLINIC	");
        data.put("Pangrio	", "	RHC PANGRIO	");
        data.put("Pangrio	", "	SAMAN SARKARCLINIC	");
        data.put("Pangrio	", "	Mehran matrnity home	");
        data.put("Pangrio	", "	SHAH LATIF CLINIC	");
        data.put("Pangrio	", "	LAL CLINIC	");
        data.put("Pangrio	", "	GHOSSIA CLINIC	");
        data.put("Pattal Kot Adu	", "	BHU pattal	");
        data.put("Pattal Kot Adu	", "	hafiz ali clinic	");
        data.put("Pattal Kot Adu	", "	bhutta maternity home	");
        data.put("Patti Ghulam ALI	", "	GRD mehbob abad	");
        data.put("Peeralabad	", "	cd peeral abad	");
        data.put("Peeralabad	", "	cd pyara khan umrani	");
        data.put("Peero Lashari	", "	AL SHIFFA CLINIC	");
        data.put("Peero Lashari	", "	Raza Clanic	");
        data.put("Peero Lashari	", "	QALANDRI CLINIC	");
        data.put("Peero Lashari	", "	TALPUR CLINIC	");
        data.put("Peero Lashari	", "	Karmi clinic	");
        data.put("Peero Lashari	", "	ohm clinic	");
        data.put("Pritamabad	", "	dr Faiz Muhammad	");
        data.put("Qaboola	", "	BHU Qurban Ali Bugti	");
        data.put("Qaboola	", "	Mehrullah Clinic	");
        data.put("Qadir Pur	", "	RD Fethey pur kamal	");
        data.put("Qadir Pur	", "	BHU Qadir Pur	");
        data.put("Qambar-I	", "	husani clanic	");
        data.put("Qambar-I	", "	al shafa clinic	");
        data.put("Qambar-I	", "	irfan clanic	");
        data.put("Qambar-I	", "	faheem maternity home	");
        data.put("Qambar-I	", "	bismillah clinic	");
        data.put("Qambar-I	", "	mozam clinic	");
        data.put("Qambar-I	", "	shajira clanic	");
        data.put("Qambar-I	", "	Ali clinic	");
        data.put("Qambar-I	", "	Mohsin Maternity Home	");
        data.put("Qambar-I	", "	muqadas	");
        data.put("Qambar-I	", "	femily welfear center	");
        data.put("Qambar-I	", "	al shafi clinic	");
        data.put("Qambar-I	", "	karachi clinic	");
        data.put("Qambar-I	", "	Sana Maternity Home	");
        data.put("Qambar-I	", "	Bilawal Maternity Home 	");
        data.put("Qambar-I	", "	khalid maternity home	");
        data.put("Qambar-I	", "	Aamina maternity home	");
        data.put("Qambar-I	", "	hamid clanic	");
        data.put("Qambar-I	", "	sana maternity home qambar	");
        data.put("Qambar-I	", "	Yousif clinic	");
        data.put("Qambar-I	", "	muzmil clinic	");
        data.put("Qambar-I	", "	paris medical center	");
        data.put("Qambar-II	", "	al ibraheem clanic	");
        data.put("Qambar-II	", "	alkrimkids care clinic	");
        data.put("Qambar-II	", "	mastoi muhlla qambar	");
        data.put("Qambar-II	", "	anmol maternity home qambar	");
        data.put("Qambar-II	", "	shoaib maternity home	");
        data.put("Qambar-II	", "	shazia clinic	");
        data.put("Qambar-II	", "	irfan clanic	");
        data.put("Qambar-II	", "	Afia maternity home	");
        data.put("Qambar-II	", "	Aqsa clinic	");
        data.put("Qambar-II	", "	Health care clinic	");
        data.put("Qambar-II	", "	mudser clinic	");
        data.put("Qambar-II	", "	shahida maternity home	");
        data.put("Qambar-II	", "	jasrani clinic qambar	");
        data.put("Qambar-II	", "	rashid  clinic	");
        data.put("Qambar-II	", "	fatah maternity home	");
        data.put("Qambar-II	", "	Haya clinic	");
        data.put("Qambar-II	", "	ikhlaq clanic	");
        data.put("Qambar-II	", "	maternity home qambar	");
        data.put("Qambar-II	", "	wali clinic	");
        data.put("Qambar-II	", "	ali jaan clinic	");
        data.put("Qambar-II	", "	liza clanic	");
        data.put("Qambar-II	", "	THQ qambar	");
        data.put("Qambar-II	", "	Ghulam hyder nonari hospital	");
        data.put("Qambar-III	", "	al hussaini child cair clanic	");
        data.put("Qambar-III	", "	Ali clinic	");
        data.put("Qambar-III	", "	halar hospital qambar	");
        data.put("Qambar-III	", "	Ali clinic	");
        data.put("Qambar-III	", "	alshafa clinic	");
        data.put("Qambar-III	", "	sagar clanicq	");
        data.put("Qambar-III	", "	sachal sarmast clinic	");
        data.put("Qambar-III	", "	massab	");
        data.put("Quba Sher Khan	", "	alshafa clinic	");
        data.put("Quba Sher Khan	", "	BHU Notal	");
        data.put("Quba Sher Khan	", "	manzor clinic	");
        data.put("Qubo Saeed Khan	", "	rehman clanic	");
        data.put("Qubo Saeed Khan	", "	amir clanic	");
        data.put("Qubo Saeed Khan	", "	sheraz clanic	");
        data.put("Qubo Saeed Khan	", "	sarwer clinic	");
        data.put("Qubo Saeed Khan	", "	sindho clinic	");
        data.put("Qubo Saeed Khan	", "	Rahman clinic	");
        data.put("Qubo Saeed Khan	", "	fareeda meternity home	");
        data.put("Qubo Saeed Khan	", "	shakeel clinic	");
        data.put("Qubo Saeed Khan	", "	shoaib clinic	");
        data.put("Qubo Saeed Khan	", "	nahid clinic	");
        data.put("Qubo Saeed Khan	", "	Rahela meternity home	");
        data.put("Qubo Saeed Khan	", "	bismullah clinic	");
        data.put("Qubo Saeed Khan	", "	sajjad clinic	");
        data.put("Qubo Saeed Khan	", "	RHC Qubo	");
        data.put("Qubo Saeed Khan	", "	al shams clanic	");
        data.put("Qubo Saeed Khan	", "	Al shafa clanic	");
        data.put("Qubo Saeed Khan	", "	mohsin clinic	");
        data.put("Rahim Abad 18	", "	Basic Health Unit Meray Shah	");
        data.put("Rahim Abad 18	", "	basic healthunit	");
        data.put("Rahim Abad 18	", "	Rural Dispensary Rahim Abad	");
        data.put("Rahim Yar Khan (Deh)	", "	MCH center	");
        data.put("Rahim Yar Khan (Deh)	", "	rural dispensari chak no 118 P	");
        data.put("Rahim Yar Khan (Deh)	", "	bhu chack116p	");
        data.put("Rahim Yar Khan (Deh)	", "	Alfarooq Clinic	");
        data.put("Rajan Kalan	", "	RHC Rajan pur kalan	");
        data.put("Rajo Khanani	", "	HORRAIN CLINIC	");
        data.put("Rajo Khanani	", "	RHC RAJHO KHANANI B TYPE	");
        data.put("Rajo Khanani	", "	MANZOOR CLINIC AND MATERNITY HOME	");
        data.put("Rajo Khanani	", "	ZAID CLINIC	");
        data.put("Rajo Khanani	", "	AL SHIFFA CLINIC	");
        data.put("Ramze Pur	", "	bhu goth allah yar khoso	");
        data.put("Rang Pur	", "	RD jhalarin  shumali	");
        data.put("Rang Pur	", "	RHC Rang Pur	");
        data.put("Rang Pur	", "	Haider clinic and maternity home	");
        data.put("Rangay Khan S-16	", "	Basi Health unit	");
        data.put("Rangay Khan S-16	", "	Rural Dispensary	");
        data.put("Ranwati	", "	noor clinic	");
        data.put("Rasool Pur  14	", "	Basic Health Unit Sadi Sultan	");
        data.put("Rasool Pur  14	", "	Basic Health Unit routi shreef	");
        data.put("Rohilan Wali	", "	RHC Rohila wali	");
        data.put("Rojhan Jamali	", "	RHC Rojhan Jamali	");
        data.put("Roshan Bhait	", "	Basic Health Unit Chak No 5 NP	");
        data.put("Sabay Wala	", "	Rehan clinic jahan pur	");
        data.put("Sabay Wala	", "	BHU thatha chandair	");
        data.put("Sabay Wala	", "	family health clinic  jatoi road sabay wala	");
        data.put("Sakran	", "	nasir clinic	");
        data.put("Sakran	", "	BHU Paniyan	");
        data.put("Sakran	", "	Irfan clinic	");
        data.put("Sakran	", "	Hameed clinic	");
        data.put("Sakran	", "	CD Sakran	");
        data.put("Sameji	", "	c d chuta khan jamali	");
        data.put("Sanghar-II	", "	distict head quarter	");
        data.put("Sanghar-II	", "	hamza clinic	");
        data.put("Sanghar-II	", "	khatri clinic	");
        data.put("Sanghar-II	", "	rajpoot clinic	");
        data.put("Sanghar-II	", "	shoeb clinic	");
        data.put("Sanghar-II	", "	kareem dino wassan	");
        data.put("Sanghar-II	", "	liaqat clinic	");
        data.put("Sanghar-II	", "	madni clinic	");
        data.put("Sanghar-II	", "	Abdul Sattar Khattak Clinic	");
        data.put("Sanghar-II	", "	haniya clinic sanghar	");
        data.put("Sanghar-II	", "	zuhra jafri clinic and maternity home	");
        data.put("Sanghar-II	", "	maternity home	");
        data.put("Sanghar-II	", "	Rizwan Clinic	");
        data.put("Sanghar-II	", "	soni ultrasound	");
        data.put("Sanghar-II	", "	razi clinic	");
        data.put("Sanghar-II	", "	dr bhagchand herdasani clinic	");
        data.put("Sanghar-II	", "	bhati maternity clinic	");
        data.put("Sanghar-II	", "	mughal clinic	");
        data.put("Sanghar-II	", "	doc farhat mahmood clinic sanghar	");
        data.put("Sanghar-II	", "	abdul rahman chield clinic	");
        data.put("Sanghar-II	", "	manoher cli ic	");
        data.put("Sanghar-II	", "	Awami clinic	");
        data.put("Sanghar-II	", "	dr saima maternity home	");
        data.put("Sanghar-II	", "	strita hospital	");
        data.put("Sanjarpur	", "	Rural Health Centre Sanjar Pur	");
        data.put("Sanjarpur	", "	Al Kareem Hospital Sanjar Pur Hospital Road Kandeer Road	");
        data.put("Sarhari	", "	ahmed clinic	");
        data.put("Sarhari	", "	altaf clinic	");
        data.put("Sarhari	", "	RHC Sarhari	");
        data.put("Sarhari	", "	dr waheed ali lakho clinic	");
        data.put("Sathar Pir	", "	district council dispensary	");
        data.put("Seerani	", "	Alshfa	");
        data.put("Seerani	", "	BISMAA CLINIC	");
        data.put("Seerani	", "	Dua	");
        data.put("Seerani	", "	sawan clanic	");
        data.put("Seerani	", "	DUAA CLINIC	");
        data.put("Seerani	", "	BISMILLAH CLINIC	");
        data.put("SEET PUR	", "	GRD chah yad gar	");
        data.put("SEET PUR	", "	Ali clinic and meternity home	");
        data.put("SEET PUR	", "	BHU Latti	");
        data.put("SEET PUR	", "	Bissmillah family clinic	");
        data.put("SEET PUR	", "	RHC	");
        data.put("Sejha	", "	RHC sejha	");
        data.put("SHadi Khan Munda	", "	BHU shadi khan munda	");
        data.put("Shah Jamal	", "	Fatima Meterinty Home	");
        data.put("Shah Jamal	", "	clinic baray khawateen	");
        data.put("Shah Jamal	", "	Al shifa clinic and meterinty home	");
        data.put("Shah Jamal	", "	RHC Shah jamal	");
        data.put("Shah Pur 25	", "	BHU Ahsan Pur	");
        data.put("Shah Pur 25	", "	BHU shah pur	");
        data.put("Shah Pur 25	", "	Alrehmat Hospital	");
        data.put("Shah Sikandar	", "	jazib child care clinic	");
        data.put("Shah Sikandar	", "	sobia clinic	");
        data.put("Shah Sikandar	", "	GD salim soomro	");
        data.put("Shah Sikandar	", "	Farman Ali clinic	");
        data.put("Shah Sikandar	", "	Darul Sehat	");
        data.put("Shah Sikandar	", "	Dr faqeer mohmmad gujar clinic	");
        data.put("Shah Sikandar	", "	Dc Dispensary	");
        data.put("Shah Sikandar	", "	Darul Shifa Dispensary	");
        data.put("Shah Sikandar	", "	Kaif Clinic	");
        data.put("Shahdad Kot-I	", "	Behter zandgi center shahdadkot	");
        data.put("Shahdad Kot-I	", "	Nooran maternity home	");
        data.put("Shahdad Kot-I	", "	Nursing care clinic shahdadkot	");
        data.put("Shahdad Kot-I	", "	mustafa clinic	");
        data.put("Shahdad Kot-I	", "	Tahir clinic	");
        data.put("Shahdad Kot-I	", "	nusrat maternity home	");
        data.put("Shahdad Kot-I	", "	isra metarnity home	");
        data.put("Shahdad Kot-I	", "	Salah clinic shahdadkot	");
        data.put("Shahdad Kot-I	", "	zulfqar medical center	");
        data.put("Shahdad Kot-II	", "	sajad health care facilty	");
        data.put("Shahdad Kot-II	", "	sajjad clinic	");
        data.put("Shahdad Kot-II	", "	niza clinic	");
        data.put("Shahdad Kot-II	", "	zeenat	");
        data.put("Shahdad Kot-II	", "	faizan maternity home	");
        data.put("Shahdad Kot-II	", "	THQ shahdakot	");
        data.put("Shahdad Kot-II	", "	maqsood clinic	");
        data.put("Shahdad Kot-II	", "	Behter zandgi center	");
        data.put("Shahdad Kot-II	", "	Bilawel clinic	");
        data.put("Shahdad Kot-II	", "	alshafa clinic	");
        data.put("Shahdad Kot-II	", "	Hasnain clinic	");
        data.put("Shahdad Kot-II	", "	zara medical center	");
        data.put("Shahdad Kot-II	", "	Tofeeq hospital	");
        data.put("Shahdad Kot-II	", "	Ali maternity home	");
        data.put("Shahdad Kot-II	", "	sanjay clinic shahdadkot	");
        data.put("Shahdad Kot-II	", "	kamran medicare	");
        data.put("Shahdad Kot-III	", "	bhittai clinic	");
        data.put("Shahdad Kot-III	", "	marve maternity home	");
        data.put("Shahdad Kot-III	", "	city medical center	");
        data.put("Shahdad Kot-III	", "	Batool medical center	");
        data.put("Shahdad Kot-III	", "	Alshafa medical center	");
        data.put("Shahdad Kot-III	", "	khushbo medical center	");
        data.put("Shahdad Kot-III	", "	Awami clinic	");
        data.put("Shahdad Kot-III	", "	wali clinic child	");
        data.put("Shahdad Kot-III	", "	shahryar clinic	");
        data.put("Shahdadpur-IV	", "	SIMS shahdadpur	");
        data.put("Shahdadpur-IV	", "	irfan child clinic	");
        data.put("Shahdadpur-IV	", "	Mustafa Clinic	");
        data.put("Shahdadpur-IV	", "	Qadir Dad clinic	");
        data.put("Shahdadpur-IV	", "	habib clinic and maternity home	");
        data.put("Shahdadpur-IV	", "	saima saleem clinic and maternity home	");
        data.put("Shahdadpur-IV	", "	Hashim Clinic and mayernity home	");
        data.put("Shahdadpur-IV	", "	sahil clinic	");
        data.put("Shahdadpur-IV	", "	dr khair u nisa clinic	");
        data.put("Shahdadpur-IV	", "	Amir Clinic	");
        data.put("Shahdadpur-IV	", "	Ashraf medical centre	");
        data.put("Shahdadpur-IV	", "	mudsar maternity hosptal	");
        data.put("Shahdadpur-IV	", "	anny clinic	");
        data.put("Shahdadpur-IV	", "	Khuram Clinic and Maternity Home	");
        data.put("Shahdadpur-IV	", "	shadad clinic and maternity home	");
        data.put("Shahdadpur-IV	", "	ali clinic	");
        data.put("Shahdadpur-IV	", "	Hussain Medical centre	");
        data.put("Shahdadpur-IV	", "	Baby Care Clinic	");
        data.put("Shahdadpur-IV	", "	naeem clinic	");
        data.put("Shahdadpur-IV	", "	Nihal Clinic	");
        data.put("Shaher Sultan	", "	Sajida perveen clinic	");
        data.put("Shaher Sultan	", "	fatma clinic shaher sultan	");
        data.put("Shaher Sultan	", "	Al aziz memorial hospital	");
        data.put("Shaher Sultan	", "	Ayesha clinic	");
        data.put("Shaher Sultan	", "	RHC Shaher Sultan	");
        data.put("Shaher Sultan	", "	Shamim rehani maternity home	");
        data.put("Shaher Sultan	", "	Raza clinic and maternity home	");
        data.put("Shaher Sultan	", "	Ganwa private hospital	");
        data.put("Shahpur Chakar	", "	Rural Health Centre	");
        data.put("Shahpur Chakar	", "	al rehman clinic	");
        data.put("Shahpur Chakar	", "	bhatai clinic	");
        data.put("Shahpur Chakar	", "	DCD Ahmed Abad	");
        data.put("Shahpur Chakar	", "	clinic	");
        data.put("Shahpur Chakar	", "	nisha clinic and maternity home	");
        data.put("Shahpur Chakar	", "	Murtaza clinic	");
        data.put("Shahpur Chakar	", "	bhatai clinic	");
        data.put("Shareen 47	", "	BHU Kot karam khan	");
        data.put("Shedani Sharif L-112	", "	Rural Dispensory Malkani	");
        data.put("Shedani Sharif L-112	", "	Rural Dispensory Jamalabad	");
        data.put("Shedani Sharif L-112	", "	Bhu shadani sharef Allah jawaya lar	");
        data.put("Sheh	", "	CD Goth Ramzan	");
        data.put("Sheh	", "	BHU Orhaki	");
        data.put("Sheikh Umar	", "	sheikh umar	");
        data.put("Sibi Jadeed	", "	BHU Sibi Jadeed	");
        data.put("Sijawal	", "	bhitai clanic	");
        data.put("Sijawal	", "	Bismillah clanic	");
        data.put("Sijawal	", "	G nabi clanic	");
        data.put("Sijawal	", "	rashid clanic	");
        data.put("Sijawal	", "	bhatai clinic	");
        data.put("Sijawal	", "	GD sajawaljunejo	");
        data.put("Sijawal	", "	al shafa clanic	");
        data.put("Sijawal	", "	iqra clanic	");
        data.put("Sijawal	", "	al shifa dua child health care clanic	");
        data.put("Silra	", "	hyder clinic	");
        data.put("Silra	", "	Alkidmat medical center	");
        data.put("Silra	", "	hamdard clanic	");
        data.put("Silra	", "	fiza clinic	");
        data.put("Silra	", "	bismullah clinic shahdadkot	");
        data.put("Silra	", "	babir clinic	");
        data.put("Sinawan	", "	Ali hospital	");
        data.put("Sinawan	", "	Abdullah clinic	");
        data.put("Sinawan	", "	Alshifa clinic	");
        data.put("Sinawan	", "	fatima zahra clinic	");
        data.put("Sinawan	", "	Alshifa clinic	");
        data.put("Sinawan	", "	sinwan	");
        data.put("Sinawan	", "	Alshifa clinic	");
        data.put("Sinawan	", "	daya choka	");
        data.put("Sinawan	", "	new jtoi clinic	");
        data.put("Sinawan	", "	Eysha maternity home	");
        data.put("Sinawan	", "	rubeena ashraf clinic	");
        data.put("Sinawan	", "	kashif abad	");
        data.put("Sinawan	", "	Private clinic	");
        data.put("Sinawan	", "	Rehman clinic	");
        data.put("Sinawan	", "	batool clinic	");
        data.put("Sinawan	", "	shagufta clinic	");
        data.put("Sinawan	", "	Ameer clinic and miternity home	");
        data.put("Sinawan	", "	eman clinic	");
        data.put("Sinjhoro	", "	M sardar araen child clinic	");
        data.put("Sinjhoro	", "	bilal medical center	");
        data.put("Sinjhoro	", "	Manwani Clinic	");
        data.put("Sinjhoro	", "	Amaar Clinic	");
        data.put("Sinjhoro	", "	kiran clinic	");
        data.put("Sinjhoro	", "	jinnah medical center	");
        data.put("Sinjhoro	", "	faimly planing center	");
        data.put("Sinjhoro	", "	inrahim medical center	");
        data.put("Sinjhoro	", "	Naveed Clinic	");
        data.put("Sinjhoro	", "	talka hospital sinjhoro	");
        data.put("Sinjhoro	", "	aftab ultra sound and maternity home	");
        data.put("Sobdrani 1	", "	BHU Monder Kot	");
        data.put("Sobdrani 1	", "	CD Kehar Kot	");
        data.put("Sobdrani 1	", "	CD HAJI MUHAMMAD IBRAHIM JAMALI	");
        data.put("Sommiani	", "	BHU Mithri	");
        data.put("Sommiani	", "	MCH Centre Sonmiyani	");
        data.put("Sommiani	", "	BHU Dam	");
        data.put("Sommiani	", "	BHU Bhira	");
        data.put("Sommiani	", "	CD Sonmiyani	");
        data.put("Sommiani	", "	BHU kuch kuraro	");
        data.put("Sonak 60	", "	BHU Sonak	");
        data.put("Sonak 60	", "	Mamoona Clinic	");
        data.put("Sonak 60	", "	RD chak no 72	");
        data.put("South Walpat	", "	BHU shuli bith village	");
        data.put("South Walpat	", "	CD moosani village	");
        data.put("South Walpat	", "	BHU jam yousaf abad dnda	");
        data.put("Sultanpur	", "	BHU	");
        data.put("Sultanpur	", "	BHU	");
        data.put("Sultanpur	", "	Dhanak meternity home	");
        data.put("Taaj Pur	", "	BHU Taaj Pur	");
        data.put("Talhar	", "	MEMON MEDICARE CLINIC	");
        data.put("Talhar	", "	HUSSAINI CLINIC	");
        data.put("Talhar	", "	MAQWANA CLINIC	");
        data.put("Talhar	", "	JAMALI CLINIC	");
        data.put("Talhar	", "	GC CLINIC AND MATERNITY HOME	");
        data.put("Talhar	", "	ALI CLINIC	");
        data.put("Talhar	", "	Hajani medical centre	");
        data.put("Talhar	", "	RHC  A TALHAR	");
        data.put("Talhar	", "	TEE LAKAHANI CLINIC	");
        data.put("Talhar	", "	HOTANI MATERNITY HOME	");
        data.put("Talhar	", "	AMAAN CLINIC	");
        data.put("Talhar	", "	HUSSAIN BUX CLINIC	");
        data.put("Taliri	", "	Doaba	");
        data.put("Taliri	", "	Talha clinic	");
        data.put("Tando Adam-III	", "	chishty babay clinic and maternity home	");
        data.put("Tando Adam-III	", "	Juman Shah Clinic	");
        data.put("Tando Adam-III	", "	uzair clinic	");
        data.put("Tando Adam-III	", "	Taluka Head Quarter THQ Tando adam	");
        data.put("Tando Adam-III	", "	azeem serwer clinic	");
        data.put("Tando Adam-III	", "	siddique clinic	");
        data.put("Tando Bago	", "	MEMON CLINIC	");
        data.put("Tando Bago	", "	AZEEM CLINIC	");
        data.put("Tando Bago	", "	SAFWAAN	");
        data.put("Tando Bago	", "	Talkua Hospital	");
        data.put("Tando Bago	", "	GULZAR CILINIC	");
        data.put("Tando Bago	", "	AL SHIFFA CLINIC	");
        data.put("Tando Bago	", "	LAL CLINIC	");
        data.put("Tando Bago	", "	Sindh Medical Centre	");
        data.put("Tando Bago	", "	AYAAN CLINIC	");
        data.put("Tando Bago	", "	MALEER CLINIC	");
        data.put("Tando Bago	", "	SEERAA CLINIC	");
        data.put("Tando Bago	", "	VISHANDAS CLINIC	");
        data.put("Tando Bago	", "	laar medical centere	");
        data.put("Tando Ghulam Ali	", "	sindh Maternity Home	");
        data.put("Tando Ghulam Ali	", "	sindh ultrasound clanic	");
        data.put("Tando Ghulam Ali	", "	RHC TENDO GHULAM ALI	");
        data.put("Tarai	", "	sadam clanic	");
        data.put("Tarai	", "	ABDUL JABAR RAHEEMOO	");
        data.put("Tarai	", "	SINDH CLINIC	");
        data.put("Tarai	", "	MAHEE MATERNITY HOME	");
        data.put("Taranda Gurgage 100	", "	BHU Kanjki Wala	");
        data.put("Tharri	", "	RHC THARRI	");
        data.put("Thatha Gurmani	", "	thatta gurmani	");
        data.put("Thatha Gurmani	", "	yousif sergical hospita	");
        data.put("Thatta Qureshi	", "	BHU Thatta Qureshi	");
        data.put("Thatta Qureshi	", "	GRD Kachi Jai	");
        data.put("Thool Chosool	", "	Gd mahmood abad	");
        data.put("Thool Chosool	", "	muhammady clanic	");
        data.put("Thul Khair Mohammad R-57	", "	BHU Rukan Pur	");
        data.put("Thul Khair Mohammad R-57	", "	RD Dodi Sangi	");
        data.put("Tibbi Gul Muhammad 58	", "	BHU Tibi Gul Muhammad	");
        data.put("Town S	", "	al khalid clinic	");
        data.put("Trianda Mohammad Pan	", "	Rural Health Center Taranda Muhammad Panah	");
        data.put("Trianda Saway Khan	", "	RHC Taranda Saway khan	");
        data.put("UC city 3	", "	seemab clinic	");
        data.put("UC city 3	", "	bushra clinic	");
        data.put("UC1", "	ayesha zcha bcha center	");
        data.put("UC1", "	hasan clinic	");
        data.put("UC1", "	Mahar hospital	");
        data.put("UC1", "	MNCH	");
        data.put("UC1", "	bhu pirhar sharqi	");
        data.put("Umar Pur Janobi", "	BHU umer pur janoobi	");
        data.put("Union Council 1", "	jamali clinic	");
        data.put("Union Council 1", "	Ekta Health Clinic	");
        data.put("Union Council 1", "	Al Rasool Medical Center	");
        data.put("Union Council 1", "	Karachi General Hospital	");
        data.put("Union Council 1", "	Basit Clinin	");
        data.put("Union Council 1", "	hasan child health care clinic	");
        data.put("Union Council 1", "	Qurban Clinic	");
        data.put("Union Council 1", "	umair clinic	");
        data.put("Union Council 1", "	karachi clinic	");
        data.put("Union Council 1", "	Dr Bashir Ahmed Abro Clinic	");
        data.put("Union Council 1", "	Zaffar Clinic	");
        data.put("Union Council 1", "	mother and child health	");
        data.put("Union Council 2", "	nazar clinic	");
        data.put("Union Council 2", "	rashim health care clinic	");
        data.put("Union Council 2", "	Alshifa Clinic	");
        data.put("Union Council 2", "	Shifa Clinic	");
        data.put("Union Council 2", "	Shahid Clinic	");
        data.put("Union Council 2", "	chandka clinic	");
        data.put("Union Council 2", "	al qadir clinic	");
        data.put("Union Council 2", "	District Head Quarter Hospital	");
        data.put("Union Council 2", "	Dr Zahid Hussain Clinic	");
        data.put("Union Council 2", "	women hospital	");
        data.put("Union Council 2", "	MCH center Usta Muhammad	");
        data.put("Union Council 2", "	city clinic sobth por dera allah yer	");
        data.put("Union Council 2", "	New Awami Clinic	");
        data.put("Union Council 2", "	jawad clinic	");
        data.put("Union Council 2", "	Samina Clinic	");
        data.put("Union Council 2", "	Raza Clinic	");
        data.put("Union Council 2", "	health care clinic	");
        data.put("Union Council 2", "	Pervez health Clinic	");
        data.put("Union Council 2", "	karachi baby care clinic	");
        data.put("Union Council 2", "	Navid Clinic	");
        data.put("Union Council 2", "	Tehsil Head Quarter Hospital	");
        data.put("Union Council 2", "	larkana clinic	");
        data.put("Union Council 2", "	naveed clinic	");
        data.put("Union Council 3", "	irfan clinic	");
        data.put("Union Council 3", "	liaqat clinic	");
        data.put("Union Council 3", "	MCHC Centre Dera Allahyar	");
        data.put("Union Council 3", "	Shahzeb clinic	");
        data.put("Union Council 3", "	maham materinty home	");
        data.put("Union Council 3", "	Islamabad clinic	");
        data.put("Union Council 3", "	al shehbaz clinic	");
        data.put("Union Council 3", "	Yar Muhammad Clinic	");
        data.put("Union Council 4", "	Alghani Maternity home	");
        data.put("Union Council 4", "	quetta clinic	");
        data.put("Union Council 4", "	jeelani clinic	");
        data.put("Union Council 4", "	zaib medical centre	");
        data.put("Urban Jatoi", "	Nasreen mayernity home	");
        data.put("Urban Jatoi", "	Maternity home clinic	");
        data.put("Urban Jatoi", "	Maternity home and clinic	");
        data.put("Urban Jatoi", "	City medical and surgical complex	");
        data.put("Urban Kot Adu # 2	", "	Riffat meternity home	");
        data.put("Urban Kot Adu # 2	", "	frha ghafoor clinic	");
        data.put("Urban Kot Adu # 2	", "	sajida tahir	");
        data.put("Urban Kot Adu # 2	", "	iram habib clinic	");
        data.put("Urban Kot Adu # 2	", "	rafia clinic	");
        data.put("Urban Kot Adu # 2	", "	khan hospital	");
        data.put("Urban Kot Adu # 2	", "	al noor metrnity	");
        data.put("Urban Kot Adu # 2	", "	THQ kot adu	");
        data.put("Urban Kot Adu # 2	", "	ameen cliniv	");
        data.put("Urban Kot Adu-1	", "	mehmoodkot	");
        data.put("Urban Kot Adu-1	", "	qasba gujrat	");
        data.put("Urban Kot Adu-1	", "	budh	");
        data.put("Urban Kot Adu-1	", "	ghazi ghat	");
        data.put("Urban Kot Adu-1	", "	shazia clinic	");
        data.put("Usman Koria	", "	BHU Usman koria	");
        data.put("Usman Koria	", "	BHU Meran pur	");
        data.put("Uthal City	", "	Uthal madical centre	");
        data.put("Uthal City	", "	Al Qaim clinc	");
        data.put("Uthal City	", "	Al Mustfa Clinc	");
        data.put("Uthal City	", "	Zubair clinc	");
        data.put("Uthal City	", "	MCH Centre	");
        data.put("Uthal City	", "	Babar Medical centre	");
        data.put("Uthal City	", "	New bhati clinc	");
        data.put("Uthal City	", "	Al shafa clinc	");
        data.put("Uthal City	", "	BHU Fida hussain shah	");
        data.put("Uthal City	", "	Jamali clinc	");
        data.put("Uthal City	", "	Al shifa clinc	");
        data.put("Uthal City	", "	Haseeb clinc	");
        data.put("Uthal City	", "	Sohai clinc	");
        data.put("Uthal City	", "	DHQ Hospital	");
        data.put("Uthal City	", "	Jholy lal clinc	");
        data.put("Uthal City	", "	ZUBAIR CLINC	");
        data.put("Utra Sandila	", "	BHU Utra sandila	");
        data.put("Vaince", "BHU Vaince");
        data.put("Vaince", "Aysha zacha bacha center");
        data.put("Waan Pitafi", "RHC baseera");
        data.put("Waan Pitafi", "RD waan patafi");
        data.put("Wagan", "anmol clinic");
        data.put("Wagan", "maryam hospital");
        data.put("Wagan", "kashif clanic");
        data.put("Wagan", "hamid clanic");
        data.put("Wagan", "mumtaz clanic");
        data.put("Wagan", "zarina maternity home");
        data.put("Wagan", "adil clanic");
        data.put("Wagan", "ali clinic");
        data.put("Wagan", "nawaz clanic");
        data.put("Wagan", "haider clanic");
        data.put("Wagan", "yasir clanic");
        data.put("Wagan", "Rhc wagan qambar");
        data.put("Wah Kohna 66", "bhu chak no 125 P");
        data.put("Wah Kohna 66", "BHU chak no 137 P");
        data.put("Wandhar", "bhu wandhar");
        data.put("Warah", "jot clinic");
        data.put("Warah", "bismillah clinic");
        data.put("Warah", "Qazi maternity home");
        data.put("Warah", "murk clinic");
        data.put("Warah", "Huwul shafi clincic");
        data.put("Warah", "mehran clinic warah");
        data.put("Warah", "Qamer clinic warah");
        data.put("Warah", "yasir child cair clinic");
        data.put("Warah", "sarfraz clinic");
        data.put("Warah", "Mehran medicare clinic");
        data.put("Warah", "Hira clinic");
        data.put("Warah", "ghulam sarwar bhutto clinic");
        data.put("Warah", "alshafa");
        data.put("Warah", "Aziz child care clinic");
        data.put("Warah", "Family well fare center warah");
        data.put("Warah", "Dua meternity home warah");
        data.put("Warah", "Ayaz clanic");
        data.put("Warah", "Al shafa health clanic");
        data.put("Warah", "Raja clanic");
        data.put("Warah", "THQ warah");
        data.put("Wayaro", "BHU Sukan");
        data.put("Wayaro", "CD Ahora");
        data.put("Wayaro", "BHU Gacheri");
        data.put("Wayaro", "Sub Health centre SHC");
        data.put("Wayaro", "CD Chhilnwari");
        data.put("Wayaro", "CD Bambri");
        data.put("Winder", "Winder Madical centre");
        data.put("Winder", "Jamali clinc Winder");
        data.put("Winder", "Marvi clinc and maternity home");
        data.put("Winder", "BHU Goth Zaman");
        data.put("Winder", "Karachi Madical Centre");
        data.put("Winder", "Mehran Clinc Winder");
        data.put("Winder", "Bhitai clinc");
        data.put("Winder", "RHC Winder");
        data.put("Zafarabad 119", "BHU zafarAbad");
        data.put("Zafarabad 119", "Basic Health Unit Saidpur");
        data.put("Zahir Pir", "Maternity Home");
        data.put("Zahir Pir", "Maternity home khan colony");
        data.put("Zahir Pir", "Mansha Hospital and Maternity Home");
        data.put("Zahir Pir", "RD Rural Dispensary");
        data.put("Zahir Pir", "RHC Zahir pir");
        data.put("Zahir Pir", "Al Shifa Hospital And Materniy Home");


        List<String> list = new ArrayList<>();
        Collection<String> coll = data.get(tehsil);

        list.add("Select");
        for (String item : coll) {
            list.add(item);
        }


        return list;
    /*    // Creating adapter for spinner
        ArrayAdapter<String> dataAdapter = new ArrayAdapter<String>(getActivity(),
         android.R.layout.simple_spinner_item, list_UC);

        // Drop down layout style - list view with radio button
        dataAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);

        // attaching data adapter to spinner
        sp_UC.setAdapter(dataAdapter);
        sp_UC.setSelection(coll_district.size());*/

    }

}
